//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensoDll.Dll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class individualPurchas
    {
        public int iPurchasesId { get; set; }
        public string purschaseDesc { get; set; }
        public int tripLookUp_tripId { get; set; }
        public int personId_personId { get; set; }
        public int purchaseDesc_descId { get; set; }
        public string purchaseDescMisc { get; set; }
        public string transactionId { get; set; }
        public string amount { get; set; }
    
        public virtual personId personId { get; set; }
        public virtual purchaseDesc purchaseDesc { get; set; }
        public virtual tripLookUp tripLookUp { get; set; }
    }
}
