//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensoDll.Dll.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExpensoEntities : DbContext
    {
        public ExpensoEntities()
            : base("name=ExpensoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<individualPurchas> individualPurchases { get; set; }
        public virtual DbSet<personId> personIds { get; set; }
        public virtual DbSet<purchaseDesc> purchaseDescs { get; set; }
        public virtual DbSet<purchaseExpens> purchaseExpenses { get; set; }
        public virtual DbSet<TripAdvance> TripAdvances { get; set; }
        public virtual DbSet<tripGroup> tripGroups { get; set; }
        public virtual DbSet<tripLookUp> tripLookUps { get; set; }
    
        public virtual ObjectResult<sp_GetPurchaseDesc_Result> sp_GetPurchaseDesc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPurchaseDesc_Result>("sp_GetPurchaseDesc");
        }
    
        public virtual ObjectResult<sp_GetTripGroup_Result> sp_GetTripGroup(Nullable<int> trip_id)
        {
            var trip_idParameter = trip_id.HasValue ?
                new ObjectParameter("trip_id", trip_id) :
                new ObjectParameter("trip_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTripGroup_Result>("sp_GetTripGroup", trip_idParameter);
        }
    
        public virtual ObjectResult<sp_GetTripMembers_Result> sp_GetTripMembers(Nullable<int> tripId)
        {
            var tripIdParameter = tripId.HasValue ?
                new ObjectParameter("tripId", tripId) :
                new ObjectParameter("tripId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTripMembers_Result>("sp_GetTripMembers", tripIdParameter);
        }
    
        public virtual ObjectResult<sp_GetTripName_Result> sp_GetTripName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTripName_Result>("sp_GetTripName");
        }
    
        public virtual int sp_InsertIndividualExpense(string purchaseDesc, Nullable<int> tripId, Nullable<int> personId, Nullable<int> purchaseId, string purchaseDescMisc, string transactionId, Nullable<double> amount)
        {
            var purchaseDescParameter = purchaseDesc != null ?
                new ObjectParameter("purchaseDesc", purchaseDesc) :
                new ObjectParameter("purchaseDesc", typeof(string));
    
            var tripIdParameter = tripId.HasValue ?
                new ObjectParameter("tripId", tripId) :
                new ObjectParameter("tripId", typeof(int));
    
            var personIdParameter = personId.HasValue ?
                new ObjectParameter("personId", personId) :
                new ObjectParameter("personId", typeof(int));
    
            var purchaseIdParameter = purchaseId.HasValue ?
                new ObjectParameter("purchaseId", purchaseId) :
                new ObjectParameter("purchaseId", typeof(int));
    
            var purchaseDescMiscParameter = purchaseDescMisc != null ?
                new ObjectParameter("purchaseDescMisc", purchaseDescMisc) :
                new ObjectParameter("purchaseDescMisc", typeof(string));
    
            var transactionIdParameter = transactionId != null ?
                new ObjectParameter("transactionId", transactionId) :
                new ObjectParameter("transactionId", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertIndividualExpense", purchaseDescParameter, tripIdParameter, personIdParameter, purchaseIdParameter, purchaseDescMiscParameter, transactionIdParameter, amountParameter);
        }
    
        public virtual int sp_InsertPurchaseExpenses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertPurchaseExpenses");
        }
    
        public virtual ObjectResult<sp_GetPurchaseExpenses_Result> sp_GetPurchaseExpenses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPurchaseExpenses_Result>("sp_GetPurchaseExpenses");
        }
    }
}
