//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensoDll.Dll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseExpens
    {
        public int pExpenseId { get; set; }
        public int tripLookUp_tripId { get; set; }
        public int personId_personId { get; set; }
        public int purchaseDesc_descId { get; set; }
        public int purchaseAmount { get; set; }
        public string purcahsedesc { get; set; }
        public System.DateTime enteredDate { get; set; }
        public string transactionId { get; set; }
        public string purchasedesc { get; set; }
    
        public virtual personId personId { get; set; }
        public virtual purchaseDesc purchaseDesc1 { get; set; }
        public virtual tripLookUp tripLookUp { get; set; }
    }
}
